services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: react-dnd
    restart: always
    ports:
      - "3001:80"
    environment:
      - NODE_ENV=production
    networks:
      - app-network
    # volumes:
    #   - ./:/app
    #   - /app/node_modules

  # backend:
  #   image: your-backend-image
  #   container_name: backend-api
  #   restart: unless-stopped
  #   ports:
  #     - "5000:5000"
  #   environment:
  #     - NODE_ENV=production
  #   networks:
  #     - app-network

networks:
  app-network:
    driver: bridge